name: 'haskell-docs'

on:
  push:
    paths:
      - '.github/workflows/haskell-docs.yml'
  pull_request:
    paths:
      - '.github/workflows/haskell-docs.yml'
      - 'clash-shockwaves/**'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.10.3'
          cabal-version: '3.14.2.0'
      - name: Check cabal file
        run: |
          cd $GITHUB_WORKSPACE/clash-shockwaves
          ghc --version
          cabal check
      - name: Compile library to docs
        if: '!cancelled()'
        run: |
          cd $GITHUB_WORKSPACE/clash-shockwaves
          cabal haddock --builddir ./hackage-dist --haddock-for-hackage --enable-doc --minimize-conflict-set
      - name: Upload Haddock docs
        uses: actions/upload-artifact@v4
        if: '!cancelled()'
        with:
          name: Haddock docs for Hackage
          path: clash-shockwaves/hackage-dist/clash-shockwaves*.tar.gz
          if-no-files-found: error
